# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.parent_knn_across_groups <- function(x, groups, n_parents, leaf_size = 40L) {
    .Call(`_geowarp_parent_knn_across_groups`, x, groups, n_parents, leaf_size)
}

.parent_knn <- function(x, n_parents, leaf_size = 40L) {
    .Call(`_geowarp_parent_knn`, x, n_parents, leaf_size)
}

.quad_form_diag <- function(A, x) {
    .Call(`_geowarp_quadFormDiag`, A, x)
}

.unique_rows <- function(input) {
    .Call(`_geowarp_uniqueRows`, input)
}

.deduplicate_parents <- function(parents) {
    .Call(`_geowarp_deduplicateParents`, parents)
}

vecchia_U_x_parts <- function(parents, xWarped, covarianceFunction, sigmaDeviation, sigmaSquaredNugget) {
    .Call(`_geowarp_vecchia_U_x_parts`, parents, xWarped, covarianceFunction, sigmaDeviation, sigmaSquaredNugget)
}

